-- CREATE WAREHOUSE
CREATE OR REPLACE WAREHOUSE C_CardWH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- CREATE DATABASE
CREATE OR REPLACE DATABASE C_CardDB;

-- CREATE SCHEMAS
CREATE OR REPLACE SCHEMA bronze;
CREATE OR REPLACE SCHEMA silver;
CREATE OR REPLACE SCHEMA gold;

-- CREATE STAGE
CREATE OR REPLACE STAGE bronze.my_stage;

